=== OpenTravel/OTM-DE-Compiler/schema-compiler/src/main/resources/ota2-context/schemas/OTA2_Project_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="http://www.OpenTravel.org/ns/OTA2/Project_v01_00" targetNamespace="http://www.OpenTravel.org/ns/OTA2/Project_v01_00" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified">

	<xsd:element name="Project" type="ProjectType" />
	<xsd:complexType name="ProjectType">
		<xsd:sequence>
			<xsd:element name="projectId" type="xsd:anyURI" />
			<xsd:element name="name" type="String_Short" />
			<xsd:element name="description" type="String_Long" minOccurs="0" />
			<xsd:element name="defaultContextId" type="String_Short" minOccurs="0" />
			<xsd:element ref="ProjectItemBase" minOccurs="0" maxOccurs="999" />
			<xsd:element ref="RepositoryReferences" minOccurs="0" />
			<xsd:element ref="ProjectProperties" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="ProjectItemBase" type="ProjectItemType" />
	<xsd:complexType name="ProjectItemType" abstract="true">
		<xsd:attribute name="defaultItem" type="xsd:boolean" />
	</xsd:complexType>

	<xsd:element name="ManagedProjectItem" type="ManagedProjectItemType" substitutionGroup="ProjectItemBase" />
	<xsd:complexType name="ManagedProjectItemType">
		<xsd:complexContent>
			<xsd:extension base="ProjectItemType">
				<xsd:sequence>
					<xsd:element name="Repository" type="String_Short" minOccurs="0" />
					<xsd:element name="BaseNamespace" type="xsd:anyURI" />
					<xsd:element name="Filename" type="Filename" />
					<xsd:element name="Version" type="String_Short" />
					<xsd:element name="WIPFileLocation" type="Filename" minOccurs="0" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:element name="UnmanagedProjectItem" type="UnmanagedProjectItemType" substitutionGroup="ProjectItemBase" />
	<xsd:complexType name="UnmanagedProjectItemType">
		<xsd:complexContent>
			<xsd:extension base="ProjectItemType">
				<xsd:sequence>
					<xsd:element name="FileLocation" type="Filename" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:element name="RepositoryReferences" type="RepositoryReferencesType"/>
	<xsd:complexType name="RepositoryReferencesType">
		<xsd:sequence>
			<xsd:element ref="RepositoryRef" minOccurs="0" maxOccurs="999"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="RepositoryRef" type="RepositoryRefType"/>
	<xsd:complexType name="RepositoryRefType">
		<xsd:simpleContent>
			<xsd:extension base="String_Long">
				<xsd:attribute name="repositoryId" type="String_Short" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:element name="ProjectProperties" type="ProjectPropertiesType"/>
	<xsd:complexType name="ProjectPropertiesType">
		<xsd:sequence>
			<xsd:element ref="Property" minOccurs="0" maxOccurs="999"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="Property" type="PropertyType"/>
	<xsd:complexType name="PropertyType">
		<xsd:simpleContent>
			<xsd:extension base="String_Long">
				<xsd:attribute name="key" type="String_Short" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:simpleType name="Identifier">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="([A-Za-z_][A-Za-z0-9\.\-_]*)?" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Filename">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z0-9~/\.\-\|:_\s]*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="String_Short">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="256" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="String_Long">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4096" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== OpenTravel/OTM-DE-Compiler/ota2-repository-service/src/test/resources/test-data/projects/project_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<otp:Project xmlns="http://www.w3.org/2001/XMLSchema" xmlns:otp="http://www.OpenTravel.org/ns/OTA2/Project_v01_00"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.OpenTravel.org/ns/OTA2/Project_v01_00 ../../../../../../schema-compiler/src/main/resources/ota2-context/schemas/OTA2_Project_v1.0.0.xsd">
    <otp:projectId>http://www.OpenTravel.org/projects/test/p1</otp:projectId>
    <otp:name>Test_Project</otp:name>
    <otp:description>Test description for the project.</otp:description>
    <otp:UnmanagedProjectItem defaultItem="true">
        <otp:FileLocation>../test-package_v2/library_1_p2.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>../test-package_v2/library_2_p2.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>../test-package_v1/library_1_p1.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>../test-package_v1/library_2_p1.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
</otp:Project>

=== OpenTravel/OTM-DE-Compiler/schema-compiler/src/test/resources/libraries_1_6/test-package-diff/project-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<otp:Project xmlns="http://www.w3.org/2001/XMLSchema" xmlns:otp="http://www.OpenTravel.org/ns/OTA2/Project_v01_00"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.OpenTravel.org/ns/OTA2/Project_v01_00 ../../../main/resources/ota2-context/schemas/OTA2_Project_v1.0.0.xsd">
    <otp:projectId>http://www.OpenTravel.org/projects/diff2</otp:projectId>
    <otp:name>Diff Project #1</otp:name>
    <otp:description>Test project for model-diff testing</otp:description>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>library_diff1_v1.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>library_diff1_v1_1.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
    <otp:UnmanagedProjectItem>
        <otp:FileLocation>library_diff2_v2.xml</otp:FileLocation>
    </otp:UnmanagedProjectItem>
</otp:Project>

=== OpenTravel/OTM-DE-Compiler/ota2-repository-service/src/test/resources/test-data/projects/version_test_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<otp:Project xmlns="http://www.w3.org/2001/XMLSchema" xmlns:otp="http://www.OpenTravel.org/ns/OTA2/Project_v01_00"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.OpenTravel.org/ns/OTA2/Project_v01_00 ../../../../../../schema-compiler/src/main/resources/ota2-context/schemas/OTA2_Project_v1.0.0.xsd">
    <otp:projectId>http://www.OpenTravel.org/projects/test/versions/2</otp:projectId>
    <otp:name>Version Test Project</otp:name>
    <otp:description>Test description for the project.</otp:description>
    <otp:ManagedProjectItem defaultItem="true">
    	<otp:Repository>test-repository</otp:Repository>
        <otp:BaseNamespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test</otp:BaseNamespace>
        <otp:Filename>Version_Test_1_1_0.otm</otp:Filename>
        <otp:Version>1.1.0</otp:Version>
    </otp:ManagedProjectItem>
    <otp:RepositoryReferences>
        <otp:RepositoryRef repositoryId="test-repository">http://localhost:9293/ota2-repository-service</otp:RepositoryRef>
    </otp:RepositoryReferences>
</otp:Project>
