=== OpenTravel/OTM-DE-Compiler/schema-compiler/src/main/resources/ota2-context/schemas/OTA2_LibraryCatalog_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00" 
	targetNamespace="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00"
	attributeFormDefault="unqualified" elementFormDefault="qualified">
	
	<xsd:element name="Catalog" type="Catalog"/>
	<xsd:complexType name="Catalog">
		<xsd:sequence>
			<xsd:element name="CatalogEntry" type="CatalogEntry" minOccurs="0" maxOccurs="99"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="CatalogEntry">
		<xsd:sequence>
			<xsd:element name="Namespace" type="xsd:anyURI" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Location" type="xsd:anyURI" minOccurs="1" maxOccurs="99"/>
		</xsd:sequence>
	</xsd:complexType>
	
</xsd:schema>

=== OpenTravel/OTM-DE-Compiler/schema-compiler/src/test/resources/libraries_1_5/library-catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Catalog xmlns="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00 ../../../main/resources/ota2-context/schemas/OTA2_LibraryCatalog_v1.0.0.xsd">
	
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/test-package_v1</Namespace>
		<Location>./test-package_v1/library_1_p1.xml</Location>
		<Location>./test-package_v1/library_2_p1.xml</Location>
	</CatalogEntry>
	
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/test-package_v2</Namespace>
		<Location>./test-package_v2/library_1_p2.xml</Location>
		<Location>./test-package_v2/library_2_p2.xml</Location>
	</CatalogEntry>
	
</Catalog>

=== OpenTravel/OTM-DE-Compiler/schema-compiler/src/test/resources/versions/version-catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Catalog xmlns="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.OpenTravel.org/ns/OTA2/LibraryCatalog_v01_00 ../../../main/resources/ota2-context/schemas/OTA2_LibraryCatalog_v1.0.0.xsd">
	
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01</Namespace>
		<Location>./library_v01_00.xml</Location>
	</CatalogEntry>
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01_00_01</Namespace>
		<Location>./library_v01_00_01.xml</Location>
	</CatalogEntry>
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01_01</Namespace>
		<Location>./library_v01_01.xml</Location>
	</CatalogEntry>
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01_02</Namespace>
		<Location>./library_v01_02.xml</Location>
	</CatalogEntry>
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01_02_01</Namespace>
		<Location>./library_v01_02_01.xml</Location>
	</CatalogEntry>
	<CatalogEntry>
		<Namespace>http://www.OpenTravel.org/ns/OTA2/SchemaCompiler/version-test/v01_02_02</Namespace>
		<Location>./library_v01_02_02.xml</Location>
	</CatalogEntry>
	
</Catalog>
